# Generated by Django 5.2.11 on 2026-02-05 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Kategoris',
                'db_table': 'kategori',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('nama_status', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id_produk', models.AutoField(primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(max_length=255)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=15)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.kategori')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.status')),
            ],
            options={
                'verbose_name_plural': 'Produks',
                'db_table': 'produk',
            },
        ),
    ]
